### PR TITLE
Pull Request Project 7 HTML CSS Complete

### PR DESCRIPTION
**Pull request by Salvador-ON**
This is the 7th HTML project using bootstrap

This website was designed with 4 resolution

small 320px
medium 768px
large 1024px
extra large 1200px

The live version is here and in the readme file https://rawcdn.githack.com/Salvador-ON/Using-Bootstap/c100ff9c2b0365be8ab59527881ecde5fca71018/index.html

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi @Salvador-ON !  
## Your project looks very good :+1: , however, there are just a few things that you need to fix.

#### Page structure

##### Navigation bar
* It should change with RWD breakpoints** ([link to page](https://www.newsweek.com/))

##### Main content

* The Name of `Opinion` and `Latest news` sections should be uppercase "OPINION" and "LATEST NEWS"

*  It contains `Editor's picks` section ([link to page](https://www.newsweek.com/)) after "IN THE MAGAZINE"
* It changes with RWD breakpoints** ([link to page](https://www.newsweek.com/))

#### Original version
original

#### Your version
new version


#### Implementation details

*  It references [Bootstrap CSS file](https://getbootstrap.com/docs/4.3/getting-started/introduction/#css)  screenshot from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap)
* It adds [viewport metatag](https://getbootstrap.com/docs/4.3/getting-started/introduction/#responsive-meta-tag) screenshot from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap)
*  It uses Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) screenshot from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/)

* Kindly recommended to check breakpoints
* Please delete comments in your code


screen






#### Please kindly fix the above issues and send another code review request.
` If you have any questions or need help, you can message me on slack (@ Anna Muzykina). Happy coding `

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by Salvador-ON** [comment]
I submit my commit with the next changes

Navbar change with RWD
Opinion and Latest news sections  with upper case
Editor's picks section is modified to have RWD in  768px breakpoint
Delete comments

**Comment by Anna-Myzukina** [comment]
### Good job! :+1: 

## Status [Approved]


#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
